### ISSUE TITLE
博主你好，想问问你的博客所用到的框架是什么？

### ISSUE THREAD

**Issue by DHUer** [yo1995/yo1995.github.io#6]
我也是duke ece 今年的新生，查询551作业的时候，偶尔翻到博客，从此感觉像收获了宝藏，学长写的博客给我带来了诸多启发。因此想按照博主的样式搭建一个主题类似的博客，想问问博主用到的主题和框架是什么？

**Comment by yo1995** [comment]
@DHUer 
- 框架是[Jekyll](https://jekyllrb.com/)
- 主题是https://vlthemes.com/#omnia_html ，后期自己修改过
- 551尽量自己做啦

**Comment by DHUer** [comment]
哇！感谢学长！！
